docker_playground/django/rails_to_django/micropost_app/micropost/urls.py
from django.urls import path

from .views import static_pages_view
from .views import users_view

app_name = 'micropost'
urlpatterns = [
    path('', static_pages_view.HomeView.as_view(), name="static_pages_home"),
    path('help/', static_pages_view.HelpView.as_view(), name="static_pages_help"),
    path('about/', static_pages_view.AboutView.as_view(), name="static_pages_about"),
    path('contact/', static_pages_view.ContactView.as_view(), name="static_pages_contact"),
    path('signup/', users_view.UsersView.as_view(), name="users_signup"),
]

docker_playground/django/rails_to_django/micropost_app/micropost_app/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

docker_playground/django/rails_to_django/micropost_app/micropost/models.py
from django.db import models
from django.core.validators import RegexValidator

class User(models.Model):
    """ユーザモデル"""

    name = models.CharField(verbose_name='name',
                            max_length=50)
    email = models.EmailField(verbose_name='email',
                              unique=True,
                              max_length=255,
                              validators=[RegexValidator(r'^[\w+\-.]+@[a-zA-Z\d\-.]+\.[a-zA-Z]+$', 'メールアドレスの形式ではない')])
    created_at = models.DateTimeField(verbose_name='created_at',
                                      auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='updated_at',
                                      auto_now=True)

    class Meta:
        verbose_name_plural = 'User'

docker_playground/django/rails_to_django/micropost_app/micropost/views.py
from django.views import generic
# from django.shortcuts import render

class HomeView(generic.TemplateView):
    template_name = "home.html"

class HelpView(generic.TemplateView):
    template_name = "help.html"

class AboutView(generic.TemplateView):
    template_name = "about.html"

class ContactView(generic.TemplateView):
    template_name = "contact.html"

docker_playground/django/rails_to_django/micropost_app/micropost/views/static_pages_view.py
from django.views import generic
# from django.shortcuts import render

class HomeView(generic.TemplateView):
    template_name = "static_pages/home.html"

class HelpView(generic.TemplateView):
    template_name = "static_pages/help.html"

class AboutView(generic.TemplateView):
    template_name = "static_pages/about.html"

class ContactView(generic.TemplateView):
    template_name = "static_pages/contact.html"

docker_playground/django/rails_to_django/micropost_app/micropost/views/users_view.py
from django.views import generic
# from django.shortcuts import render

class UsersView(generic.TemplateView):
    template_name = "users/new.html"

docker_playground/django/rails_to_django/micropost_app/micropost/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'vendor/css/bootstrap.min.css' %}">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/js/bootstrap.bundle.min.js' %}"></script>

    <!--[if lt IE 9]>
        <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
        </script>
    <![endif]-->
</head>
<body>
    <!-- navbar -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a id="logo" class="navbar-brand" href="{% url 'micropost:static_pages_home' %}">sample app</a>
            <div class="navbar-nav">
                <a class="nav-link" href="{% url 'micropost:static_pages_home' %}">Home</a>
                <a class="nav-link" href="{% url 'micropost:static_pages_help' %}">Help</a>
                <a class="nav-link" href="#">Log in</a>
            </div>
        </div>
    </nav>

    <div class="container">
        <!-- main content -->
        {% block contents %}{% endblock %}
        <!-- footer -->
        <footer class="footer">
            <small>
                The <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
                by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
            </small>
            <nav>
                <ul>
                    <li><a href="{% url 'micropost:static_pages_about' %}">About</a></li>
                    <li><a href="{% url 'micropost:static_pages_contact' %}">Contact</a></li>
                    <li><a href="http://news.railstutorial.org/">News</a></li>
                </ul>
            </nav>
        </footer>
    </div>
</body>
</html>

docker_playground/django/rails_to_django/micropost_app/micropost/templates/static_pages/about.html
{% extends 'base.html' %}

{% block title %}About | Rails Tutorial Sample App{% endblock %}

{% block contents %}
<div class="center bg-light p-5 my-4 rounded">
    <h1>About</h1>
    <p>
        <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
        is a <a href="https://railstutorial.jp/#ebook">book</a> and
        <a href="https://railstutorial.jp/screencast">screencast</a>
        to teach web development with
        <a href="https://rubyonrails.org/">Ruby on Rails</a>.
        This is the sample application for the tutorial.
    </p>
</div>
{% endblock %}

docker_playground/django/rails_to_django/micropost_app/micropost/templates/static_pages/contact.html
{% extends 'base.html' %}

{% block title %}Contact | Rails Tutorial Sample App{% endblock %}

{% block contents %}
<div class="center bg-light p-5 my-4 rounded">
    <h1>Contact</h1>
    <p>
        Contact the Ruby on Rails Tutorial about the sample app at the
        <a href="https://railstutorial.jp/contact">contact page</a>.
    </p>
</div>
{% endblock %}

docker_playground/django/rails_to_django/micropost_app/micropost/templates/static_pages/help.html
{% extends 'base.html' %}

{% block title %}Help | Rails Tutorial Sample App{% endblock %}

{% block contents %}
<div class="center bg-light p-5 my-4 rounded">
    <h1>Help</h1>
    <p>
        Get help on the Rails Tutorial by Django at the
        <a href="https://railstutorial.jp/help">Rails Tutorial help page</a>.
        To get help on this sample app, see the
        <a href="https://railstutorial.jp/#ebook"><em>Rails Tutorial</em></a>
    </p>
</div>
{% endblock %}

docker_playground/django/rails_to_django/micropost_app/micropost/templates/static_pages/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Rails Tutorial Sample App{% endblock %}

{% block contents %}

<div class="center bg-light p-5 my-4 rounded">
    <h1>Welcome to the Sample App</h1>

    <h2>
        This is the home page for the
        <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
        sample application.
    </h2>

    <a class="btn btn-lg btn-primary" href="{% url 'micropost:users_signup' %}">Sign up now!</a>
</div>

<a href="http://rubyonrails.org/"><img src="{% static 'assets/images/rails.png' %}" alt="Rails logo"></a>

{% endblock %}

docker_playground/django/rails_to_django/micropost_app/micropost/templates/users/new.html
{% extends 'base.html' %}

{% block title %}Sign up | Rails Tutorial Sample App{% endblock %}

{% block contents %}
<div class="center bg-light p-5 my-4 rounded">
    <h1>Sign up</h1>
</div>
<p>This will be a signup page for new users.</p>
{% endblock %}